### PR TITLE
Update Matomo ID

### PR DESCRIPTION
**Pull request by clementbiron**
Update the ID of the new Matomo account of fr.openfisca.org

### CODE REVIEW

**Comment by clementbiron** [comment]
@MattiSG can you please assign yourself in review to trigger the tests?

**Comment by MattiSG** [comment]
- I pushed this commit into the main repository, but this did not trigger any additional tests.
- The Netlify preview fails for the same reasons as https://github.com/openfisca/openfisca.org/issues/98, so all Netlify-related checks fail. This also means that deploying, which relies on Netlify, is blocked.
- I cannot review this as connecting to Matomo gives me the following error:

> Erreur: Vous devez vous connecter pour accéder à cette fonctionnalité. _(when not logged in)_
> Erreur: Vous ne pouvez pas accéder à cette ressource car elle nécessite l'accès 'view' pour le site id = 11.  _(when logged in)_

**Comment by MattiSG** [comment]
After an assessment of the contents in this website, I second @sandcha's viewpoint that this is now a full (obsolete) duplicate of openfisca.org and that most of the contents should be removed and refocused on the French community.
Thus, this change is not worth investing as much effort as we did for https://github.com/openfisca/openfisca.org/issues/98 or https://github.com/openfisca/openfisca-doc/pull/291.

@clementbiron I suggest to try and upgrade the build image from Netlify if:
1. It is easy to do so (no permissions to require).
2. This does not put the current production at risk.

Then, if the problem is solved with the build image upgrade, we could proceed with this update.
If not, then let's bring back the tracking in the main Matomo ID. We will then use filters in Matomo to separate the two websites, and if still relevant will change the tracker ID when we rewrite the website.

**Comment by clementbiron** [comment]
I have updated the Netlify build image from Ubuntu `Xenial 16.04` to `Focal 20.04` and that seems to works, see the logs https://app.netlify.com/sites/openfisca-fr/deploys/64132b93d6549f005fa62dab and the associated preview https://deploy-preview-57--openfisca-fr.netlify.app/

image

**Review by MattiSG — CHANGES_REQUESTED** [review]
I understand from @amelalili that the URL for this new account is now `stats.beta.gouv.fr`, not `stats.data.gouv.fr`.

**Comment by MattiSG** [comment]
> I have updated the Netlify build image

Thanks @clementbiron!! Everything seems to work indeed 😍

**Review by MattiSG — APPROVED** [review]
Confirmed now that the [target website](https://stats.beta.gouv.fr/index.php?module=CoreHome&action=index&idSite=11&period=day&date=yesterday#?period=day&date=yesterday&category=Dashboard_Dashboard&subcategory=1&idSite=11) is back online! 😃

**Pull request merged**
